config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :categories
  resources :articles do
    resources :votes
  end
  # resources :votes, only [:index]
  devise_for :users
  root to: 'articles#index'
  get '/votes/:id', to: 'articles#votes', as: 'votes'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :article_categories, dependent: :destroy
  has_many :categories, through: :article_categories
  has_many :votes, dependent: :destroy

  has_one_attached :main_image
  validates :main_image, presence: false,
                         blob: { content_type: ['image/jpg', 'image/jpeg', 'image/png'], size_range: 1..3.megabytes }

  validates :title, presence: true
  validates :text, length: { minimum: 15 }
  validates :category_ids, presence: { message: 'Select at least 1 category' }

  scope :ordered_by_votes, -> { sort_by { |article| article.votes.count }.reverse }
end

app/controllers/articles_controller.rb
# rubocop:disable all
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  # GET /articles or /articles.json
  def index
    @articles = Article.with_attached_main_image.all
  end

  # GET /articles/1 or /articles/1.json
  def show
    @a_params = params[:id]
    unless current_user.nil?
      @vote = Vote.find_by(user_id: current_user.id, article_id: @article.id)
      # @vote = current_user.articles.includes(:votes)
    end
  end

  # GET /articles/new
  def new
    if user_signed_in?
      @article = current_user.articles.build
    else
      redirect_to new_user_registration_path
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, alert: 'Article successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :main_image, :text, category_ids: [])
  end
end

# rubocop:enable all

app/helpers/articles_helper.rb
# rubocop:disable all

# frozen_string_literal: true

module ArticlesHelper
  def main_image(article, is_main)
    if article.main_image.attached?
      if is_main
        image_tag article.main_image, class: 'h-full object-cover max-h-full w-full bg-no-repeat bg-center'
      else
        image_tag article.main_image,
                  class: 'min-h-full bg-cover object-cover min-h-64 max-h-full bg-no-repeat bg-center md:w-full lg:w-full hover:scale-110'
      end
    else
      image_tag 'placeholder.jpeg', class: 'h-full bg-cover object-cover w-full'
    end
  end

  def most_voted_article
    @articles.ordered_by_votes.first
  end

  def highest_ranked_categories
    # etches the article with the most votes for each category
    Category.order('priority').first(4)
  end
end

# rubocop:enable all

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |f| %>
  <div class="flex items-center space-y-3 py-3 flex-col h-full">
    <%= render 'shared/errors', object: article %>
    <%= f.label :title, class:"text-lg font-bold" %>
    <%= f.text_field :title, autofocus: true, class:"focus:outline-white w-96 text-lg" %>
    <%= f.label :text, class:"text-lg font-bold" %>
    <div class="pb-3">
      <%= f.text_area :text, rows: 7, autofocus: true, class:"focus:outline-white text-lg w-96 h-36 text" %>
    </div>
    <div class="px-4 py-3 my-3 bg-gray-100 rounded-full">
      <%= f.label :main_image, class: "px-4 py-3" %>
    </div>
    <%= f.file_field :main_image, class:"px-3" %>
    <div class="px-4 py-3 my-3 bg-gray-100 rounded-full button cursor-pointer">
      <%= f.submit %>
    </div>
    <div class="bg-teal-400 rounded p-3">
      <h3 class="text-lg text-white bg-opacity-50">Select which applies:</h3>
    </div>
    <div class="checkboxes space-x-3 py-3 flex text-center items-center">
      <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="font-mono bg-blue-100 justify-center font-mono flex flex-col">
  <div class="space-y-3 py-4 flex flex-col">
    <h1 class="text-white bg-teal-400 bg-opacity-70 rounded flex items-center text-2xl font-bold justify-center space-y-6 py-6" >Editing Article</h1>
    <p class="flex items-center justify-center"><%= render 'form', article: @article %></p>
    <div class="flex justify-center items-center space-x-5">
      <p><%= link_to 'Show', @article, class:" hover:underline text-white rounded-full hover:text-blue-900 bg-blue-400 py-2 px-4" %></p>
      <p><%= link_to 'Back', articles_path, class:" hover:underline text-white rounded-full hover:text-blue-900 bg-blue-400 py-2 px-4" %></p>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="font-mono">
  <div class="h-96 border-bluegray-100 relative font-mono">
    <%= main_image(most_voted_article, true) %>
    <div class="md:p-2 space-y-4 lg:p-3 rounded absolute bottom-0 left-0 flex flex-col justify-center w-1/4 group bg-teal-100 bg-opacity-30 group hover:bg-opacity-0">
      <h2 class="flex justify-center font-bold text-lg p-2 text-white rounded bg-teal-400 group-hover:bg-teal-500 shadow group-hover:bg-opacity-80 "><%= @articles.first.title %></h2>
      <div class="flex py-2 space-y-2 justify-between text-white lg:flex lg:flex-row flex-wrap md:flex-col">
        <h3 class="bg-blue-400 space-y-2 group-hover:bg-blue-600 group-hover:bg-opacity-80 p-2 rounded text-xs"><%= truncate(@articles.first.text, length: 45, separator: ' ') %></h3>
        <p><%= link_to 'Read More', article_path(@articles.first), class:"space-y-2 group bg-yellow-300 group-hover:bg-yellow-400 p-2 rounded-full text-blue-600 group-hover:text-blue-800 text-xs italic btn btn-default group-hover:text-blue-900 shadow transition duration-300" %></p>
      </div>
    </div>
  </div>
  <div class="flex flex-row bg-gray-300 flex-wrap">
    <% highest_ranked_categories.each_with_index do |category, index| %>
      <div class="w-1/4 h-64 nax-h-full relative group">
        <%= main_image(category.articles.last, false) %>
        <div class="p-2 rounded h-full absolute bottom-0 bg-teal-100 bg-opacity-30 group hover:bg-opacity-0 w-full md:space-y-1 lg:space-y-2 flex flex-col justify-between shadow transition duration-500">
          <div class="bg-blue-400 group-hover:bg-teal-500 shadow group-hover:bg-opacity-80 w-1/3 items-center p-2 flex justify-center rounded shadow transition duration-500">
            <h2 class="font-bold lg:text-lg md:text-sm text-white underline-yellow"h2><%=category.name %></h2>
          </div>
          <div class="py-1 justify-items-center justify-center lg:flex lg:flex-row md:flex-col w-full text-white items-center lg:text-center justify-between group">
            <h3 class="space-y-2 my-2 bg-blue-400 group-hover:bg-blue-600 group-hover:bg-opacity-80 p-2 rounded text-xs"><%= truncate(category.articles.last.title, length: 35, separator: ' ') %></h3>
            <p><%= link_to 'Read More', category.articles.last, class:"space-y-2 bg-yellow-300 group-hover:bg-yellow-400 p-2 rounded-full text-blue-600 group-hover:text-blue-800 text-xs italic btn btn-default group-hover:text-blue-900 shadow transition duration-500" %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="bg-blue-100 h-full justify-center font-mono flex flex-wrap">
  <div class="space-y-3 py-4 flex flex-col">
    <h1 class="text-white bg-teal-400 bg-opacity-70 rounded flex items-center text-2xl font-bold justify-center space-y-6 py-6">Create A New Article</h1>
    <p class="flex items-center justify-center"><%= render 'form', article: @article %></p>
    <div class="flex justify-center items-center space-x-5">
      <p><%= link_to 'Show', @article, class:" hover:underline text-white rounded-full hover:text-blue-900 bg-blue-400 py-2 px-4" %></p>
      <p><%= link_to 'Back', articles_path, class:" hover:underline text-white rounded-full hover:text-blue-900 bg-blue-400 py-2 px-4" %></p>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="h-full border-bluegray-100 bg-bluegray-100 bg-opacity-50 font-mono text-white">
  <div class="bg-opacity-10 w-full object-cover absolute article-show" >
    <%= main_image(@article, false) %>
  </div>
  <div class="md:py-2 space-y-4 lg:py-3 items-center flex flex-col bg-teal-500 group">
    <h1 class="bg-teal-500 p-6 rounded bg-opacity-50 text-3xl lg:text-6xl md:text-4xl items-center relative flex text-center"><%= @article.title %></h1>
    <h3 class="bg-gradient-to-b from-transparent to-blue-700 bg-opacity-30 hover:bg-opacity-70 group text-md flex relative justify-center items-center text-center pt-16 px-16 lg:px-64 md:pt-20 md:px-20 lg:px-30 lg:pt-30 w-full text-white whitespace-pre-line min-h-96"><%= @article.text %></h3>
    <h3 class="bg-teal-500 bg-opacity-50 group text-md flex relative justify-center items-center text-center w-full uppercase text-white">Written by:<%= truncate(@article.user.username, length: 15, separator: ' ') %></h3>
    <div class="text-white group relative flex justify-center w-full py-2 px-3 rounded bg-blue-700 bg-opacity-30">
      <div class="details py-10 relative flex space-x-3 bg-transparent justify-between">
        <section class="admin flex flex-column">
          <%= @article.votes.count %>
          <div class="flex text-white items-center px-3">
            <% if @vote %>
              <%= link_to image_tag("logo-1.svg", width: "3%"), article_vote_path(@article, @vote), method: :delete %>
            <% else %>
              <%= link_to image_tag("logo-2.svg", width: "3%"), article_votes_path(@article), method: :post %>
            <% end %>
          </div>
          <div class="flex space-x-4">
            <%= link_to 'Back', articles_path, class:"text-white hover:underline hover:text-blue-500 bg:blue-300" %>
          </div>
        </section>
      </div>
    </div>