config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :categories
  resources :articles do
    resources :votes
  end
  # resources :votes, only [:index]
  devise_for :users
  root to: 'articles#index'
  get '/votes/:id', to: 'articles#votes', as: 'votes'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  @categories = Category.all
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
    # @categories.each do |category|
    #   @c_params = (params[:id])
    #   if Category.where(user_id: current_user.id, article_id: params[:id]).count > 0
    # end
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, alert: 'Category successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.fetch(:category, {})
  end
end

app/helpers/categories_helper.rb
# rubocop:disable all
# frozen_string_literal: true

module CategoriesHelper
  def fetch_articles
    @category.articles.with_attached_main_image.order('created_at desc').includes([:user])
  end

  def category_image(fetch_articles)
    if fetch_articles.main_image.attached?
      image_tag fetch_articles.main_image,
                class: 'object-cover order-first sm:order-first md:order-first lg:order-none w-full h-64 max-h-full lg:h-full'
    else
      image_tag 'placeholder.jpeg'
    end
  end
end

# rubocop:enable all

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="font-mono bg-blue-100 h-screen justify-center font-mono flex">
  <div class="space-y-3 py-4 flex flex-col">
    <h1 class="text-white bg-teal-400 bg-opacity-70 rounded flex items-center text-2xl font-bold justify-center space-y-6 py-6">Editing Category</h1>
    <h2 class="text-white bg-teal-400 bg-opacity-70 rounded flex items-center text-2xl font-bold justify-center space-y-6 py-6"><%= @category.name %></h2>
    <div class="flex justify-center items-center space-x-5">
      <%= render 'form', category: @category %>
      <p><%= link_to 'Show', @category, class:" hover:underline text-white rounded-full hover:text-blue-900 bg-blue-400 py-2 px-4" %></p>
      <p><%= link_to 'Back', categories_path, class:" hover:underline text-white rounded-full hover:text-blue-900 bg-blue-400 py-2 px-4" %></p>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Categories</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<div class="font-mono bg-blue-100 h-screen justify-center font-mono flex">
  <div class="space-y-3 py-4 flex flex-col">
    <h1 class="text-white bg-teal-400 bg-opacity-70 rounded flex items-center text-2xl font-bold justify-center space-y-6 py-6">New Category</h1>
    <%= render 'form', category: @category %>
    <div class="flex justify-center items-center space-x-5">
      <p><%= link_to 'Back', categories_path, class:" hover:underline text-white rounded-full hover:text-blue-900 bg-blue-400 py-2 px-4" %></p>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="font-mono flex-wrap w-full">
  <div class="grid w-full h-full place-items-start sm:grid-rows-2 sm:grid-cols-1 lg:grid-cols-2 grid-cols-1">
    <% fetch_articles.each_with_index do |article, index| %>
      <% if index % 4 < 2 %>
        <div class="grid sm:grid-cols-1 lg:grid-cols-2 grid-cols-1 w-full h-full">
          <%= category_image(article) %>
          <div class="flex-col space-y-4 mx-auto flex w-full bg-gray-100 text-teal-700">
            <div class="bg-teal-400 p-3 bg-opacity-70">
              <h2 class="items-center flex justify-center underline text-lg text-white" ><%= @category.name %></h2>
            </div>
            <h2 class="items-center flex justify-center font-bold md:text-sm text-md px-10 text-blue-600" ><%= article.title %></h2>
            <h2 class="items-center text-xs flex justify-center px-10" ><%= truncate(article.text, length: 150, separator: ' ') %></h2>
            <div class="flex justify-center py-3">
              <p><%= link_to 'Read More', article, class:"bg-yellow-300 hover:bg-yellow-400 p-2 rounded-full text-blue-600 hover:text-blue-800 text-xs italic btn btn-default hover:text-blue-900 shadow transition duration-500" %></p>
            </div>
          </div>
        </div>
      <% else %>
        <div class="grid sm:grid-cols-1 lg:grid-cols-2 grid-cols-1 w-full h-full">
          <div class="flex-col space-y-4 mx-auto flex w-full bg-gray-100 text-teal-700">
            <div class="bg-teal-400 p-3 bg-opacity-70">
              <h2 class="items-center flex justify-center underline text-lg text-white" ><%= @category.name %></h2>
            </div>
            <h2 class="items-center flex justify-center font-bold md:text-sm text-md px-10 text-blue-600" ><%= article.title %></h2>
            <h2 class="items-center text-xs flex justify-center px-10" ><%= truncate(article.text, length: 150, separator: ' ') %></h2>
            <div class="flex justify-center py-3">
              <p><%= link_to 'Read More', article, class:"bg-yellow-300 hover:bg-yellow-400 p-2 rounded-full text-blue-600 hover:text-blue-800 text-xs italic btn btn-default hover:text-blue-900 shadow transition duration-500" %></p>
            </div>
          </div>
          <%= category_image(article) %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="space-x-6 py-6 flex items-center text-center w-full justify-center">
    <%= link_to 'Back', articles_path, class:" hover:underline text-white rounded-full hover:text-blue-900 bg-blue-400 py-2 px-4" %>
  </div>
</div>